name: ani_sleuth
description: "Beyond the screen: Explore every detail with AniSleuth."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  flutter_spinkit: ^5.2.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  http: ^1.3.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.4.2
  visibility_detector: ^0.4.0+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9
  palette_generator: ^0.3.3+6
 

flutter:
  uses-material-design: true
  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
          - asset: assets/fonts/Poppins-Light.ttf
